---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: springboot
  name: java-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: springboot
    spec:
      containers:
      - image: aravind2389/html
        name: springboot
        ports:
        - name: springboot
          containerPort: 8080  
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: springboot
  name: springboot
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: springboot
