---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix
  labels:
    app: netflix
spec:
  replicas: 3
  selector:
    matchLabels:
      app: netflix
  template:
    metadata:
      labels:
        app: netflix
    spec:
      containers:
      - name: springboot
        image: harshagadhi/groovy:latest
        ports:
        containerPort: 8080  
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
spec:
  selector:
    app: netflix
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
