---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix
  labels:
    app: netflix
spec:
  replicas: 3
  selector:
    matchLabels:
      app: netflix
  template:
    metadata:
      labels:
        app: netflix
    spec:
      containers:
      - name: springboot
        image: aravind2389/html
        ports:
        containerPort: 8080  
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: netflix
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: netflix
